"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Info, Sparkles, Target, TrendingUp, Heart, Mail, Loader2 } from "lucide-react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { useToast } from "@/components/ui/use-toast"

export default function AboutView() {
  const { toast } = useToast()
  const [open, setOpen] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [form, setForm] = useState({
    email: "",
    subject: "",
    message: "",
  })

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { id, value } = e.target
    setForm((prev) => ({ ...prev, [id]: value }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!form.email || !form.subject || !form.message) {
      toast({
        variant: "destructive",
        title: "Missing Fields",
        description: "Please fill out all fields before sending.",
      })
      return
    }
    setIsLoading(true)

    try {
      const response = await fetch("/api/send-email", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(form),
      })

      const result = await response.json()

      if (response.ok && result.success) {
        toast({
          title: "Email Sent!",
          description: "Thank you for your feedback. We'll get back to you soon.",
        })
        setOpen(false) // Close the dialog on success
        setForm({ email: "", subject: "", message: "" }) // Reset form
      } else {
        throw new Error(result.message || "Something went wrong")
      }
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Uh oh! Something went wrong.",
        description: error instanceof Error ? error.message : "There was a problem with your request.",
      })
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen p-6 max-w-4xl mx-auto">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-12 h-12 bg-gradient-to-br from-primary to-accent rounded-xl flex items-center justify-center">
            <Info className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-foreground">About Kaio</h1>
            <p className="text-muted-foreground">Your AI-powered life coach</p>
          </div>
        </div>
      </motion.div>

      {/* App Info */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <Card className="p-6 mb-6 bg-gradient-to-br from-primary/5 to-accent/5 border-primary/20">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-16 h-16 bg-gradient-to-br from-primary to-accent rounded-2xl flex items-center justify-center">
              <Sparkles className="w-8 h-8 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-foreground">Kaio</h2>
              <p className="text-sm text-muted-foreground">Version 1.0.0</p>
            </div>
          </div>
          <p className="text-foreground leading-relaxed">
            Kaio is your personal AI life coach designed to help you achieve your fitness, nutrition, and lifestyle
            goals. Get personalized daily plans tailored to your unique needs and track your progress over time.
          </p>
        </Card>
      </motion.div>

      {/* Features */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
        <Card className="p-6 mb-6">
          <h2 className="text-xl font-bold mb-4 text-foreground">Features</h2>
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                <Sparkles className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-1">AI-Powered Plans</h3>
                <p className="text-sm text-muted-foreground">
                  Get personalized daily plans generated by advanced AI based on your specific goals and preferences.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                <Target className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-1">Goal Tracking</h3>
                <p className="text-sm text-muted-foreground">
                  Set and track your fitness, nutrition, and lifestyle goals with detailed daily checklists.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                <TrendingUp className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-1">Progress Analytics</h3>
                <p className="text-sm text-muted-foreground">
                  View your history and track completion rates to stay motivated and see your improvement over time.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                <Heart className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground mb-1">Holistic Approach</h3>
                <p className="text-sm text-muted-foreground">
                  Covers fitness, nutrition, hydration, sleep, and lifestyle habits for complete wellness optimization.
                </p>
              </div>
            </div>
          </div>
        </Card>
      </motion.div>

      {/* Technology */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
        <Card className="p-6 mb-6">
          <h2 className="text-xl font-bold mb-4 text-foreground">Built With</h2>
          <div className="flex flex-wrap gap-2">
            {["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Framer Motion", "Zustand", "AI SDK"].map(
              (tech) => (
                <span
                  key={tech}
                  className="px-3 py-1.5 bg-primary/10 text-primary rounded-lg text-sm font-medium border border-primary/20"
                >
                  {tech}
                </span>
              ),
            )}
          </div>
        </Card>
      </motion.div>

      {/* Contact */}
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
        <Card className="p-6">
          <h2 className="text-xl font-bold mb-4 text-foreground">Get in Touch</h2>
          <p className="text-sm text-muted-foreground mb-4">
            Have feedback or suggestions? We'd love to hear from you!
          </p>
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button
                variant="outline"
                className="bg-primary/10 border-primary/20 hover:bg-primary/20 text-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50"
              >
                <Mail className="w-4 h-4 mr-2" />
                Contact Us
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px] bg-white dark:bg-zinc-950">
              <form onSubmit={handleSubmit}>
                <DialogHeader>
                  <DialogTitle>Contact Us</DialogTitle>
                  <DialogDescription>
                    Please fill out the form below. We'll get back to you as soon as possible.
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="email" className="text-right">
                      Email
                    </Label>
                    <Input id="email" type="email" value={form.email} onChange={handleInputChange} className="col-span-3" placeholder="you@example.com" />
                  </div>
                  <div className="grid grid-cols-4 items-center gap-4">
                    <Label htmlFor="subject" className="text-right">
                      Subject
                    </Label>
                    <Input id="subject" value={form.subject} onChange={handleInputChange} className="col-span-3" placeholder="Feedback for Kaio" />
                  </div>
                  <div className="grid grid-cols-4 items-start gap-4">
                    <Label htmlFor="message" className="text-right pt-2">
                      Message
                    </Label>
                    <Textarea id="message" value={form.message} onChange={handleInputChange} className="col-span-3" placeholder="I have a suggestion..." />
                  </div>
                </div>
                <DialogFooter>
                  <Button type="submit" disabled={isLoading}>
                    {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    Send Message
                  </Button>
                </DialogFooter>
              </form>
            </DialogContent>
          </Dialog>
        </Card>
      </motion.div>

      {/* Footer */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="text-center mt-8 text-sm text-muted-foreground"
      >
        <p>Made with love for your personal growth journey</p>
        <p className="mt-1">© 2025 Kaio. All rights reserved.</p>
      </motion.div>
    </div>
  )
}